### PR TITLE
Run valgrind during travis ci to find memory leaks

### PR DESCRIPTION
**Pull request by iankronquist**
Fun and simple.

### CODE REVIEW

**Comment by maximecb** [comment]
Why not modify `make test` in the makefile to run valgrind if present, instead?

**Comment by iankronquist** [comment]
Yep, we could to that too. I'll try that when I have time.

**Comment by iankronquist** [comment]
@maximecb fixed.

**Comment by maximecb** [comment]
Fails the travis tests. Need to modify travis.yml to install valgrind.

**Comment by iankronquist** [comment]
Okay, let's try this again.

**Comment by iankronquist** [comment]
Travis CI passed. This should be ready to go.

**Pull request merged**
